name: sylph
description: A fast k-mer based metagenomic profiler
keywords:
  - metagenomics
  - profiling
  - taxonomy
  - k-mer
  - profile
tools:
  - sylph:
      description: A fast k-mer based metagenomic profiler
      homepage: https://github.com/bluenote-1577/sylph
      documentation: https://github.com/bluenote-1577/sylph
      tool_dev_url: https://github.com/bluenote-1577/sylph
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: FASTQ files
      pattern: "*.{fastq,fq,fastq.gz,fq.gz}"
  - database:
      type: file
      description: Sylph database
      pattern: "*.syldb"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - profile_out:
      type: file
      description: Sylph taxonomic profile output
      pattern: "*.tsv"
authors:
  - "@bluenote-1577"
maintainers:
  - "@bluenote-1577"