# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "ariba_run"
description: Run ARIBA for antimicrobial resistance gene detection
keywords:
  - antimicrobial resistance
  - AMR
  - antibiotic resistance
  - gene detection
  - microbiology
  - bacteria
  - resistance genes  
tools:
  - "ariba":
      description: "Antimicrobial Resistance Identification By Assembly"
      homepage: "https://github.com/sanger-pathogens/ariba"
      documentation: "https://github.com/sanger-pathogens/ariba/wiki"
      tool_dev_url: "https://github.com/sanger-pathogens/ariba"
      doi: "10.1099/mgen.0.000131"
      licence: ["GPL v3"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: Paired-end sequencing reads in FASTQ format
      pattern: "*.{fastq,fq,fastq.gz,fq.gz}"
  - meta2:
      type: map  
      description: |
        Groovy Map containing database information
        e.g. [ id:'card' ]
  - db:
      type: file
      description: Compressed database tar archive prepared by ariba prepareref
      pattern: "*.tar.gz"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - results:
      type: directory
      description: ARIBA output directory containing all result files
      pattern: "*/"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@nf-core"
maintainers:
  - "@nf-core"