name: ghru-readqc
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Python and core tools
  - python=3.11
  - pip
  
  # Nextflow and workflow management
  - nextflow>=23.04.0
  
  # Quality control and trimming
  - fastp=0.23.4
  
  # Species identification and genome sizing
  - sylph=0.6.1
  
  # MLST typing
  - ariba=2.14.6
  
  # Reporting
  - multiqc=1.19
  
  # General bioinformatics tools
  - seqtk
  - gzip
  
  # Python packages for helper scripts
  - pandas
  - numpy
  - biopython
  - matplotlib
  - seaborn
  
  # Additional utilities
  - wget
  - curl