name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install pixi
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash
          export PATH="$HOME/.pixi/bin:$PATH"
      - name: Install dependencies
        run: pixi install
      - name: Run ruff linting
        run: pixi run ruff check .
      - name: Run ruff formatting check
        run: pixi run ruff format --check .
      - name: Run tests
        run: |
          if [ -d "tests" ]; then
            pixi run python -m pytest tests/
          else
            echo "No tests directory found. Skipping tests."
          fi
